CREATE TYPE "TestAttemptStatus" AS ENUM ('IN_PROGRESS', 'SUBMITTED', 'EXPIRED');

ALTER TABLE "TestAttempt" ADD COLUMN "status" "TestAttemptStatus" NOT NULL DEFAULT 'IN_PROGRESS';

ALTER TABLE "Answer" ADD COLUMN "awardedScore" DOUBLE PRECISION;
ALTER TABLE "Answer" ADD COLUMN "maxScore" DOUBLE PRECISION;
ALTER TABLE "Answer" ADD COLUMN "behaviourContributions" JSONB;
ALTER TABLE "Answer" ADD COLUMN "rubricBreakdown" JSONB;
ALTER TABLE "Answer" ADD COLUMN "manualOverride" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE "Answer" ADD COLUMN "manualScore" DOUBLE PRECISION;
